[project]
name = "avatarquotes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "polars>=1.29.0",
    "pytest>=8.3.5",
]
